platform :ios, '16.0'
use_frameworks!

target 'SloMoLive' do
  # RTMP push từ iOS lên Node Media Server (NMS).
  # LFLiveKit đã được dùng trong CameraManager.swift để đẩy luồng H.264 120/240fps.
  pod 'LFLiveKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      # Cho phép build không cần code-signing trên Codemagic CI
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
